name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show project files
        run: ls -la

      - name: Check Node.js
        run: node --version

      - name: Install dependencies
        run: npm ci

      - name: Check server.js
        run: node --check server.js

      - name: Build Docker image
        run: docker build -t devops-node-app:latest .
